weather_dbt:
  outputs:
    dev:
      dbname: dwh_mega
      host: 172.18.0.100
      pass: star_net2016
      port: 5432
      schema: raw
      threads: 1
      type: postgres
      user: noc
  target: dev
